# Numpy Class - 1 Basics of numpy

In [1]:
# importing Numpy
import numpy as np

In [3]:
# creating 1D numpy array using python list
l = [1,2,3,4,5]
arr = np.array(l)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
# creating 2D numpy array using python list

l=[[1,2,3],[4,5,6]]
arr2 = np.array(l)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# creating numpy array using numpy built-in generator method
# Start point is included and end point is excluded
without_step = np.arange(0,10)
without_step = np.arange(0,10,2)

In [11]:
# creating a zeros matrix
# for 1D numpy array pass a number directly to the parameter
# NOTE: In this function, we'll pass tuple for 2-D or more D

np.zeros(5)

# for 2D or more D pass tuple as a parameter

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# creating a ones matrix
# for 1D numpy array pass a number directly to the parameter
# NOTE: In this function, we'll pass tuple for 2-D or more D

np.ones(5)

# for 2D or more D pass tuple as a parameter

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# in linspace(start,end,num_of_points) we have evenly specified number over a given interval
# start and end points are included
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [20]:
# creating a identity matrix in numpy

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
# creating array of random number
# rand() will return uniformly distributed random number between 0 and 1
# NOTE: In this function, we'll not pass tuple for 2-D or more D

np.random.rand(2,3)

array([[0.72033057, 0.27702196, 0.15978863],
       [0.19874329, 0.96849555, 0.08728738]])

In [26]:
# creating array of random number
# randn() will return normally distributed random number
# NOTE: In this function, we'll not pass tuple for 2-D or more D

np.random.randn(2,3)

array([[-0.42921408,  0.29774996,  2.03822647],
       [-0.88031861, -0.73682308,  1.87652973]])

In [34]:
# creating array of random number
# randint(low,high,size) will return integer random number from low to high number
# NOTE: In this function, we'll pass tuple for 2-D or more D
# Low is included and High is excluded
np.random.randint(1,100,(10,10))

array([[96, 44, 49, 39, 84, 24, 43, 12, 94, 25],
       [51, 48, 56, 55, 35, 34, 92, 42, 94, 91],
       [29, 43, 95, 91, 56, 73,  5, 73, 12, 25],
       [95, 62, 90, 83, 95, 54, 76, 53, 55, 69],
       [ 4,  9, 60,  3, 98, 76, 77, 43, 40, 90],
       [64, 33,  5, 63, 90,  5, 59, 54,  7, 60],
       [37, 66, 95,  5,  4,  4, 17, 83, 52, 25],
       [63, 44,  3, 58, 83, 38, 16, 42, 87, 79],
       [25, 83, 96, 37, 98, 74, 37, 78, 77, 35],
       [55, 74, 61, 17, 74, 18, 54, 64, 90, 38]])

## Important array attributes and functions

In [35]:
arr = np.arange(25)

In [36]:
ranarr = np.random.randint(0,50,10)
ranarr

array([37, 20, 44, 29,  1, 35,  6, 42,  2, 19])

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ranarr.max()

44

In [41]:
ranarr.min()

1

In [42]:
ranarr.argmax()

2

In [44]:
ranarr.argmin()

4

In [46]:
ranarr.shape

(10,)

In [47]:
arr.dtype

dtype('int32')

# Numpy Class - 2 Indexing and Slicing

In [48]:
import numpy as np

In [49]:
arr = np.arange(0,11)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
# to get single element from an array
arr[8] 

8

In [54]:
# to get multiple element from an array (slicing)
# start index is included and stop is excluded
arr[1:5]

array([1, 2, 3, 4])

In [55]:
# to get everything
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
# broadcasting on numpy array
arr[5:] = 100

In [57]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100, 100])

In [59]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
# as we know that whenever we assign an 1 array to another then the a view (reference)
# is made to an original array. This is because numpy doesn't make copies of arrays to avoid memory problem

arr_copy = arr[0:5]
arr_copy[:] = 5
arr_copy

array([5, 5, 5, 5, 5])

In [64]:
arr

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10])

In [71]:
# For the above output we can see that when we broadcast the value of "arr_copy to 5" then we see this broadcasting in the 
# orignal array "arr", as arr_copy is refering to arr  
# Now to make an another copy of original array use np.copy().

arr_copy = arr.copy()
arr_copy[:] = 5
arr_copy

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [73]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
# Indexing 2-D array
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d[0]

array([1, 2, 3])

In [91]:
# indexing a specific element form the 2D array
# arr[row][col]
arr_2d[0][1]

2

In [93]:
# arr[row,col]

arr_2d[0,1]

2

In [104]:
arr_2d[0:2][1:]

# the above statement is equivalent to the below statements

a = arr_2d[0:2]
a[1:]

array([[4, 5, 6]])

In [105]:
arr_2d[0:2,1:]

array([[2, 3],
       [5, 6]])

## Boolean operation on numpy array

In [111]:
bool_arr = arr > 5

In [109]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [110]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

## Numpy Class - 3 Numpy Operation

In [112]:
import numpy as np

In [113]:
arr = np.arange(0,11)

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
# Array with Array
# to perform add, sub, multiply, div on numpy array use +,-,*,/ operator respectively

arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [116]:
# Array with Scalar

arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [117]:
arr / arr

C:\Users\saini\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [118]:
1 / arr

C:\Users\saini\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [119]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

## Universal function

In [120]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [121]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [122]:
np.max(arr)

10

In [123]:
np.min(arr)

0

In [124]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [125]:
np.log(arr)

C:\Users\saini\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [128]:
np.remainder(arr,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0], dtype=int32)